# HUD
no_display
legacy_layout=false

# Style
text_color=FFFFFF
font_size=24
round_corners=8
background_color=000000
background_alpha=0.4
position=top-left
table_columns=4

# Items
cpu_stats
cpu_text=CPU
core_bars
cpu_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_mhz
cpu_temp

gpu_stats
gpu_text=GPU
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_core_clock
gpu_junction_temp

vram
vram_color=AD64C1
gpu_mem_clock
gpu_mem_temp

ram
ram_color=C26693
swap

fps
frame_timing
frametime_color=00FF00

exec_name
show_fps_limit
present_mode
winesync
time

toggle_hud=F1

# Frame limiting
fps_limit=239, 0
fps_limit_method=early

toggle_fps_limit=F2

# Logging
autostart_log=0
output_folder=~/.cache/mango
log_duration=30
log_interval=100

toggle_logging=F3
