context.properties = {
     support.dbus                           = true
     link.max-buffers                      = 64
     mem.warn-mlock                        = true
     mem.allow-mlock                       = true
     mem.mlock-all                         = true
     clock.power-of-two-quantum            = true
     log.level                             = 2
     cpu.zero.denormals                    = true

     default.clock.rate          = 48000
     default.clock.allowed-rates = [ 96000 48000 44100 ]
     default.clock.quantum       = 64
     default.clock.min-quantum   = 32
     default.clock.max-quantum   = 256
}

# context.spa-libs = {}
#
# context.modules = {}
#
# context.objects = {}
#
# context.exec = []
#
# node.rules = []
#
# device.rules = []
