# 6 band sink equalizer
#
# Copy this file into a conf.d/ directory such as
# ~/.config/pipewire/filter-chain.conf.d/
#
context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Headphone Filter"
            media.name       = "headphone Filter"
            filter.graph = {
                nodes = [
                    {
                        type = lv2
                        name = "eq"
                        plugin = "http://lsp-plug.in/plugins/lv2/para_equalizer_x16_stereo"
                        control = {
                              "mode" = 0
                              "ife_l" = 0
                              "ife_r" = 0
                              "ofe_l" = 0
                              "ofe_r" = 0
                              "rfe_l" = 0
                              "rfe_r" = 0

                              "ft_0" = 1
                              "fm_0" = 1
                              "f_0" = 53
                              "g_0" = 0.741310238838196
                              "q_0" = 1

                              "ft_1" = 1
                              "fm_1" = 0
                              "f_1" = 105
                              "g_1" = 1.88364911079407
                              "q_1" = 0.709999978542328
                              
                              "ft_2" = 1
                              "fm_2" = 0
                              "f_2" = 140
                              "g_2" = 0.803526103496552
                              "q_2" = 0.699999988079071

                              "ft_3" = 1
                              "fm_3" = 0
                              "f_3" = 1350
                              "g_3" = 0.683911681175232
                              "q_3" = 1.20000004768372

                              "ft_4" = 1
                              "fm_4" = 0
                              "f_4" = 1830
                              "g_4" = 0.683911681175232
                              "q_4" = 1.20000004768372
                              
                              "ft_5" = 1
                              "fm_5" = 0
                              "f_5" = 3230
                              "g_5" = 0.881048858165741
                              "q_5" = 4

                              "ft_6" = 1
                              "fm_6" = 0
                              "f_6" = 4420
                              "g_6" = 0.732824504375458
                              "q_6" = 5

                              "ft_7" = 1
                              "fm_7" = 0
                              "f_7" = 5600
                              "g_7" = 0.645654201507568
                              "q_7" = 2.5
                              
                              "ft_8" = 1
                              "fm_8" = 0
                              "f_8" = 7000
                              "g_8" = 1.33352148532867
                              "q_8" = 1.20000004768372

                              "ft_9" = 3
                              "fm_9" = 0
                              "f_9" = 10000
                              "g_9" = 0.891250908374786
                              "q_9" = 0.709999978542328
                          }
                    }
                ],
                inputs = [
                    "eq:in_l",
                    "eq:in_r"
                ],
                outputs = [
                    "eq:out_l",
                    "eq:out_r"
                ],
            }

	          audio.channels = 2
	          audio.position = [ FL FR ]
            capture.props = {
                node.name   = "headphone_filter"
                node.passive   = true
            }
            playback.props = {
                node.name   = "headphone_filter"
                target.object = "alsa_output.pci-0000_00_1f.3.analog-stereo"
                node.passive   = true
            }
        }
    }
]
