stream.properties = {
  resample.quality = 10
  node.latency = 256/48000
}

stream.rules = []

pulse.properties = {
    pulse.min.req          = 128/48000     # 2.7ms
    pulse.default.req      = 256/48000     # 20 milliseconds
    pulse.min.frag         = 128/48000     # 2.7ms
    pulse.default.frag     = 48000/48000   # 2 seconds
    pulse.default.tlength  = 48000/48000   # 2 seconds
    pulse.min.quantum      = 128/48000     # 2.7ms
    pulse.default.format   = F32
    pulse.default.position = [ FL FR ]
}

module.rt.args = {
    nice.level   = -20
    rt.prio      = 83
}
pulse.cmd = []

pulse.rules = []
