# 6 band sink equalizer
#
# Copy this file into a conf.d/ directory such as
# ~/.config/pipewire/filter-chain.conf.d/
# #
# context.modules = [
# { name = libpipewire-module-filter-chain
#   args = {
#     node.description = "Microphone Filter"
#       media.name       = "Microphone Filter"
#       filter.graph = {
#         nodes = [
#   #       {
#   #           type = lv2
#   #           name = gate_stereo
#   #           plugin = http://lsp-plug.in/plugins/lv2/gate_stereo
#   #           config = {
#   # 
#   #           }
#   #           control = {
#   #           }
#   #       }
#         ]
#       }
#     audio.channels = 2
#       audio.position = [ FL FR ] 
#       capture.props = {
#         node.name   = "gate_stereo"
#           media.class = Audio/Sink
#       }
#     playback.props = {
#       node.name   = "gate_stereo"
#         node.passive = true
#     }
#   }
# }
# ]
