wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/Anime/kawaii-cat-girl-3840x2160-26545.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/doge.jpg
    fit_mode = cover
}
