source = ~/.config/hypr/colors.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor = 
    path = ~/Pictures/Wallpapers/wallpaper  # Must be file or hard link, symlinks are broken.
    color = rgba(25, 20, 20, 1.0)

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 3 # 0 disables blurring
    blur_size = 4
    noise = 0.0117
    contrast = 1.1
    brightness = 0.8 # 0.8172
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

label {
    monitor =
    
    text = $TIME
    font_size = 110
    font_family = $font
    color = rgba(200, 200, 200, 1.0)

    shadow_passes = 4
    shadow_size = 5

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    
    text = Hey $USER!
    font_size = 40
    font_family = $font
    color = rgba(c8c8c8ff)

    # shadow_passes = 3
    # shadow_size = 5

    position = 0, 0
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 350, 55
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    
    outline_thickness = 3
    outer_color = $on_primary_container
    inner_color = $surface_container_highest

    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    
    font_color = rgba(101010cc)
    font_family = $font # Noto Sans
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
    
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty

    # rounding = 8 # -1 means complete rounding (circle/oval)
    position = 0, 13%
    halign = center
    valign = bottom
}

