[global]
  separator_color = foreground
  highlight = "{{colors.on_primary_container.default.hex}}"
  background = "{{colors.surface_container.default.hex}}f0"

[urgency_low]
	foreground = "{{colors.on_surface_variant.default.hex}}"

[urgency_normal]
	foreground = "{{colors.on_surface_variant.default.hex}}"

[urgency_critical]
	foreground = "{{colors.error.default.hex}}"
